sudo: false
language: java
services:
- docker
cache:
  directories:
  - "$HOME/.cache"
before_install:
  - echo "installing private repository"
  - git clone https://${BITBUCKET_UN_APP_PW}@bitbucket.org/usdot-jpo-ode/jpo-ode-private.git jpo-ode-private
  - cd jpo-ode-private
  - mvn clean
  - mvn install
  - cd ..
  - echo "installing package_cloud distribution gem"
  - gem install package_cloud
install: true #must disable pre-installation of dependencies because it fails due to missing oss.runtime dependency install 
script: mvn clean install -DskipTests
deploy:
  branches:
    only:
    - master
  script: package_cloud push schwartz_matthew2/jpo-security target/fedgov-cv-security-2016-1.0.0-SNAPSHOT.jar 
