sudo: false
language: java
services:
- docker
cache:
  directories:
  - "$HOME/.cache"
before_install:
  - echo "installing private repository"
  - git clone https://${BITBUCKET_UN_APP_PW}@bitbucket.org/usdot-jpo-ode/jpo-ode-private.git jpo-ode-private
  - cd jpo-ode-private
  - mvn clean
  - mvn install
  - cd ..
#  - echo "installing 1609.2 security library repository"
#  - git clone https://github.com/usdot-jpo-ode/jpo-security.git fedgov-cv-security-2016
#  - cd fedgov-cv-security-2016
#  - mvn clean
#  - mvn -DskipTests install
#  - cd ..
install: true #must disable pre-installation of dependencies because it fails due to missing oss.runtime dependency install 
script: mvn clean install -DskipTests
deploy:
  provider: script
  script: "cp .travis.settings.xml $HOME/.m2/settings.xml && mvn deploy"
  skip_cleanup: true
  on:
    tags: true 
